### ISSUE TITLE
how to plot your figure

### ISSUE THREAD

**Issue by 1145284121** [mahaoxiang822/Boundary-Guided-Context-Aggregation#3]
Hi, Thank you for your work and for providing the code. How can we visualize the attention feature map and feature similarity? 
![FBCF150A848B231756935E9E91BED42E](https://user-images.githubusercontent.com/41956449/146913758-29fe7cac-551c-4792-a0fb-35b9cd70ec60.jpg)

**Comment by mahaoxiang822** [comment]
Hi, thanks for your attention.

(1) To visualize the attention map (the size of it is (H*W)*(H*W)) , you can select a position and get it's attention. Add the code like the one shown below in attention module.
```
# sim_map_div_C size: batch_size*(H*W)*(H*W)
visual = sim_map_div_C[:, position, :]
visual = visual.view(batch_size, 1, *x.size()[2:])
```
(2) To visualize the feature similarity,  you can select one position of the feature and calculate the cosine similarity. Add the code like the one shown below to the feature you want to visualize.
```
# feature size: batch_size*C*H*W
point= feature[:,:,h,w].unsqueeze(2).unsqueeze(3)
point = point.expand(feature.size())
visual = torch.cosine_similarity(point,feature,dim=1)
```

**Comment by 1145284121** [comment]
(1)Thank you very much for your answer. I'm still confused about question 2. Do I understand correctly. After I use hook to obtain the feature (at this time, the feature size is B C H/8 W/8), then select a point on the feature map and calculate the similarity, and finally interpolate it to the original image size (H W)? Here is the code I used for testing.

(2)Or should we first interpolate the feature map to the size of the original image and then select a point for calculation?

#H W C
img = input.permute(0, 2, 3, 1).cpu().numpy().squeeze()

#B C H' W'
fea = feature[2]

#B C 1 1 -> B C -> B C H' W'
point = fea[:, :, 77, 77].unsqueeze(2).unsqueeze(3)
point = point.expand(fea.size())

#B C H' W' -> B C H W
visual = torch.cosine_similarity(point, fea, dim=1).squeeze()
visual /= visual.max()
visual *= 255
visual = visual.cpu().numpy().astype('uint8')
visual = cv2.resize(visual, (2048, 1024))

heatmap = cv2.applyColorMap(visual, cv2.COLORMAP_JET)
heatmap = cv2.addWeighted(heatmap, 0.7, img.astype('uint8'), 0.3, 0)

cv2.imwrite('./figure/result/heatmap_' + 'test' heatmap)
cv2.imwrite('./figure/result/raw_'  + 'test', img)
cv2.imshow('heatmap', heatmap)
cv2.waitKey(10000)

atten.remove()

**Comment by mahaoxiang822** [comment]
There's no much difference between the two methods in my opinion. I use the first one.
