### ISSUE TITLE
F1 boundary score code

### ISSUE THREAD

**Issue by YangParky** [mahaoxiang822/Boundary-Guided-Context-Aggregation#4]
Hi! Could you tell me how to evaluate the edge which is reported in your paper. I want to evaluate it locally.

**Comment by YangParky** [comment]
Hi! Could you tell me how to evaluate the edge which is reported in your paper. I want to evaluate it locally.

**Comment by mahaoxiang822** [comment]
Sorry for the late reply, I have update the code for boundary and interior region accuracy evaluation. (util/f_boundary.py, util/f_interior.py)

**Comment by YangParky** [comment]
Thanks for your reply. 
I'm strange about your mIoU value which is computred on boundary, is there any way to figure it out?

**Comment by mahaoxiang822** [comment]
![image](https://user-images.githubusercontent.com/36100173/155836567-1f26e122-139a-4ec4-8a74-38ed603838c0.png)
We report the accuracy of boundary region using F-score in our paper. If you want to get the mIoU, you can calculate it by
`mIoU = TP/(TP+FP+FN)`

**Comment by YangParky** [comment]
Thanks for your patient reply.
